import os
env = Environment(ENV = os.environ)

env.Append(LIBS=["png16","gsl","gslcblas"])
env.Append(CXXFLAGS=["-std=c++11","-g","-Wall","-O3","-I/usr/include/libpng16"])
env.Append(LINKFLAGS=[])

env.Program("driver",["main.cpp","parse.cpp","dump_png.cpp","driver_state.cpp","shaders.cpp"])
